--- #YAML:1.0
name:                Term-Twiddle
version:             2.72
abstract:            Twiddles a thingy while-u-wait
license:             ~
author:              
    - Scott Wiersdorf <scott@perlcode.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Time::HiRes:                   1.3
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
